programming_languages = []
print(programming_languages)
programming_languages.append('python')
print(programming_languages)
programming_languages.append('go')
print(programming_languages)
programming_languages.insert(0, 'c#')
print(programming_languages)
programming_languages.reverse()
print(programming_languages)
programming_languages.sort()
print(programming_languages)
del programming_languages[0]
print(programming_languages)
programming_languages.insert(0, 'elixir')
print(programming_languages)
programming_languages.remove('go')
print(programming_languages)
programming_languages.pop()
print(programming_languages)
programming_languages.append('ruby')
programming_languages.append('julian')
print(sorted(programming_languages))
print(programming_languages)
programming_languages.sort(reverse=True)
print(sorted(programming_languages, reverse=True))
print(programming_languages)
